networks:
  k6:
  grafana:

services:
  db:
    image: mysql:latest
    container_name: redis-study-mysql-container
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=0000
      - MYSQL_DATABASE=testdb
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/initdb.d:/docker-entrypoint-initdb.d
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    networks:
      - k6
      - grafana
    ports:
      - "8086:8086"
      - "8085:8088"
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
      - INFLUXDB_ADMIN_USER_PASSWORD=admin123
      - INFLUXDB_HTTP_AUTH_ENABLED=false
  grafana:
    image: bitnami/grafana:latest
    networks:
      - grafana
    ports:
      - "3000:3000"
  k6:
    image: loadimpact/k6:latest
    container_name: k6
    networks:
      - k6
    ports:
      - "6565:6565"
    volumes:
      - ./k6-test:/scripts
    command: run /scripts/test2.js --out influxdb=http://influxdb:8086/k6
  redis:
    image: "redis:latest"
    container_name: "redis-service"
    ports:
      - "6379:6379"
